version: 2

project_name: agent-smith

builds:
  - id: agents
    main: ./main.go
    binary: agents
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X agent-smith/cmd.Version={{ .Version }}

archives:
  - builds: [agents]
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums.txt

release:
  prerelease: auto
  draft: false
